CREATE DATABASE SALES

USE SALES


select * from amazon
select count(*) from amazon


select 
	count(*) as total_rows,
	count(amount) as non_null_amount
from amazon




--- write a query for Total Revenue ?
select 
	Round(sum(Amount),2) as total_revenue
from amazon
where status = 'Shipped - Delivered to Buyer'


-- WRITE THE QUERY FOR TOTAL ORDER'S COUNT ?
SELECT 
	COUNT(DISTINCT Order_ID) AS TOTAL_ORDERS 

FROM AMAZON


-- WRITE THE QUERY FOR CANCELLED VS DELIVERED ORDERS COUNT ?

SELECT 
	STATUS,
	COUNT(*) AS ORDER_COUNT
FROM AMAZON
WHERE STATUS IN ( 'Shipped - Delivered to Buyer','CANCELLED')
GROUP BY STATUS
  
	-- WHAT IS OVERALL STATUS DISTRIBUTION ?
  
		SELECT 
			STATUS,
			COUNT(*) AS TOTAL_COUNT
		FROM AMAZON
		GROUP BY STATUS
		ORDER BY TOTAL_COUNT DESC

  

-- DATA QUALITY CHECK
-- WRITE THE QUERY TO FIND DELIVERED ORDERS WHERE AMOUNT = 0 AND QTY = 0

SELECT 
	DATE,Order_ID,STATUS,courier_status,Fulfilment,Amount,Qty
FROM AMAZON
WHERE STATUS = 'Shipped - Delivered to Buyer' AND Amount = 0 OR Qty = 0



-- BUSINESS INSIGHT
-- WRITE A QUERY FOR TOP 5 PRODUCTS BY REVENUE

SELECT	TOP 5
	Category,
	ROUND(SUM(Amount),2) AS TOTAL_REVENUE
FROM AMAZON
GROUP BY Category
ORDER BY TOTAL_REVENUE DESC

-- WRITE THE QUERY FOR TOP 5 CATEGORIES BY REVENUE AND ONLY FOR DELIVERED ORDERS ?

SELECT TOP 5
	Category,
	SUM(AMOUNT) AS TOTAL_REVENUE
FROM AMAZON
WHERE STATUS = 'Shipped - Delivered to Buyer'
GROUP BY Category
ORDER BY TOTAL_REVENUE DESC


-- WRITE THE QUERY FOR MONTHLY REVENUE TREND
  
SELECT 
	YEAR(DATE) AS YEAR_,
	MONTH(DATE) AS MONTH_,
	SUM(Amount) AS TOTAL_REVENUE
FROM AMAZON
WHERE STATUS = 'Shipped - Delivered to Buyer'
GROUP BY YEAR(DATE) ,MONTH(DATE)


-- WRITE THE QUERY FOR CANCELLATION PERCENTAGE'

SELECT 
	COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS,
	COUNT(DISTINCT CASE
		WHEN STATUS = 'Cancelled' THEN ORDER_ID
	END) AS CANCELLED_ORDERS,
	ROUND(
		COUNT (DISTINCT CASE
			WHEN STATUS = 'Cancelled' THEN ORDER_ID
		END) * 100
		/ COUNT(DISTINCT ORDER_ID),
		2) AS CANCELLED_PERCENTAGE
FROM AMAZON
